version: 2
jobs:
   build:
     docker:
       - image: circleci/node:10-stretch
     steps:
       - checkout
       - run: sudo apt-get install -y python-pip
       - run: pip install -q awscli --upgrade
       - run: npm install
       - run: npm run build
       - run: aws s3 sync dist/ s3://hiroshi.toycode.com/ --delete
