version: 2
jobs:
   build:
     environment:
         PATH: /home/circleci/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     docker:
       - image: circleci/node:8-stretch
     steps:
       - checkout
       - run: sudo apt-get install -y awscli
       - run: npm ci
       - run: npm run build
       - run: aws s3 sync dist/ s3://hiroshi.toycode.com/ --delete
