version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8-stretch
     steps:
       - checkout
       - run: sudo apt-get install -y python-pip
       - run: pip install awscli --upgrade --user
       - run: aws --version
       - run: npm ci
       - run: npm run build
       - run: aws s3 sync dist/ s3://hiroshi.toycode.com/ --delete
